Update smithay
Looks like smithay update was missing causing the build to fail on:
```
error[E0308]: mismatched types
   --> src/state.rs:696:65
    |
696 |         let compositor_state = CompositorState::new::<Self>(dh, &handle);
    |                                ----------------------------     ^^^^^^^ expected `Sender<CompositorEvent>`, found `&LoopHandle<'_, State>`
    |                                |
    |                                arguments to this function are incorrect
    |
    = note: expected struct `calloop::channel::Sender<CompositorEvent>`
            found reference `&LoopHandle<'static, state::State>`
```